/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface CAppContainer {
    }
    interface CAppLoader {
        "src": string;
        "type": string;
    }
    interface CAppMenu {
        "items": any[];
        "mode": string;
    }
    interface CAppMenuItem {
        "base": string;
        "item": any;
        "level": number;
    }
    interface CAppRoot {
        "controller": any;
    }
    interface CAppRouter {
        "base": string;
        "routes": any[];
    }
}
declare global {
    interface HTMLCAppContainerElement extends Components.CAppContainer, HTMLStencilElement {
    }
    var HTMLCAppContainerElement: {
        prototype: HTMLCAppContainerElement;
        new (): HTMLCAppContainerElement;
    };
    interface HTMLCAppLoaderElement extends Components.CAppLoader, HTMLStencilElement {
    }
    var HTMLCAppLoaderElement: {
        prototype: HTMLCAppLoaderElement;
        new (): HTMLCAppLoaderElement;
    };
    interface HTMLCAppMenuElement extends Components.CAppMenu, HTMLStencilElement {
    }
    var HTMLCAppMenuElement: {
        prototype: HTMLCAppMenuElement;
        new (): HTMLCAppMenuElement;
    };
    interface HTMLCAppMenuItemElement extends Components.CAppMenuItem, HTMLStencilElement {
    }
    var HTMLCAppMenuItemElement: {
        prototype: HTMLCAppMenuItemElement;
        new (): HTMLCAppMenuItemElement;
    };
    interface HTMLCAppRootElement extends Components.CAppRoot, HTMLStencilElement {
    }
    var HTMLCAppRootElement: {
        prototype: HTMLCAppRootElement;
        new (): HTMLCAppRootElement;
    };
    interface HTMLCAppRouterElement extends Components.CAppRouter, HTMLStencilElement {
    }
    var HTMLCAppRouterElement: {
        prototype: HTMLCAppRouterElement;
        new (): HTMLCAppRouterElement;
    };
    interface HTMLElementTagNameMap {
        "c-app-container": HTMLCAppContainerElement;
        "c-app-loader": HTMLCAppLoaderElement;
        "c-app-menu": HTMLCAppMenuElement;
        "c-app-menu-item": HTMLCAppMenuItemElement;
        "c-app-root": HTMLCAppRootElement;
        "c-app-router": HTMLCAppRouterElement;
    }
}
declare namespace LocalJSX {
    interface CAppContainer {
    }
    interface CAppLoader {
        "src"?: string;
        "type"?: string;
    }
    interface CAppMenu {
        "items"?: any[];
        "mode"?: string;
        "onCardinal:config:getRouting"?: (event: CustomEvent<any>) => void;
    }
    interface CAppMenuItem {
        "base"?: string;
        "item"?: any;
        "level"?: number;
    }
    interface CAppRoot {
        "controller"?: any;
    }
    interface CAppRouter {
        "base"?: string;
        "onCardinal:config:getRouting"?: (event: CustomEvent<any>) => void;
        "routes"?: any[];
    }
    interface IntrinsicElements {
        "c-app-container": CAppContainer;
        "c-app-loader": CAppLoader;
        "c-app-menu": CAppMenu;
        "c-app-menu-item": CAppMenuItem;
        "c-app-root": CAppRoot;
        "c-app-router": CAppRouter;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "c-app-container": LocalJSX.CAppContainer & JSXBase.HTMLAttributes<HTMLCAppContainerElement>;
            "c-app-loader": LocalJSX.CAppLoader & JSXBase.HTMLAttributes<HTMLCAppLoaderElement>;
            "c-app-menu": LocalJSX.CAppMenu & JSXBase.HTMLAttributes<HTMLCAppMenuElement>;
            "c-app-menu-item": LocalJSX.CAppMenuItem & JSXBase.HTMLAttributes<HTMLCAppMenuItemElement>;
            "c-app-root": LocalJSX.CAppRoot & JSXBase.HTMLAttributes<HTMLCAppRootElement>;
            "c-app-router": LocalJSX.CAppRouter & JSXBase.HTMLAttributes<HTMLCAppRouterElement>;
        }
    }
}
